name: "Bug"
description: "진행할 작업을 상세하게 기록해주세요."
title: "[ Project ]: "

body:
  - type: dropdown
    id: project-type
    attributes:
      label: Project
      description: 어떤 프로젝트의 작업인가요?
      options:
        - ow-landing
        - ow-main
        - pixel-main
        - pixel-admin
        - design-system
        - config
    validations:
      required: true
  - type: textarea
    id: why
    attributes:
      label: Why need this change?
      description: 해당 작업이 필요한 이유를 작성해주세요!
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: Description
      description: 작업 상세 내용을 적어주세요.
    validations:
      required: false
